# Generated by Django 5.1 on 2024-08-27 16:19

import userauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userauth.models.CustomUserManager()),
            ],
        ),
    ]
